FROM python:3.10

WORKDIR /app

COPY . .

RUN pip install poetry && \
    poetry install --no-root && \
    apt update && \
    apt install -y git zsh && \
    sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)" && \
    git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions && \
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting && \
    cp .zshrc ~/.zshrc

CMD ["zsh"]